<?php

/**
 * @file
 * KMaps term reference field type for Mandala.
 */

/**
 * Implements hook_theme().
 */
function shanti_kmaps_fields_theme(): array {
  return [
    'kmaps_field_tags' => [
      'variables' => [
        'tags' => [],
      ],
      'template' => 'kmaps-field-tags',
    ],
    'kmaps_popover' => [
      'variables' => [
        'label' => '',
        'domain' => '',
        'kid' => 0,
        'ftypes' => [],
        'desc' => '',
        'defs' => [],
        'tree' => [],
        'links' => [],
      ],
      'template' => 'kmaps-popover',
    ],
  ];
}
