name: mandala
type: drupal11
docroot: drupal/web
composer_root: drupal
php_version: "8.3"
webserver_type: apache-fpm
database:
  type: mariadb
  version: "10.11"
composer_version: "2"
nodejs_version: "18"
use_dns_when_possible: true

hooks:
  post-start:
    - exec-host: if [ ! -d "drupal/vendor" ]; then ddev composer install --prefer-dist; fi

web_environment:
  - DRUPAL_HASH_SALT=temporary-local-dev-only
